### ISSUE TITLE
Remove requirement to manually update the IAM role

### ISSUE THREAD

**Issue by cplee** [stelligent/cfn-nag-pipeline#1]
There is an issue [awslabs/serverless-application-model#389] with the SAM policy template `CodePipelineLambdaPolicyTemplate` that uses invalid resources for the policy statement.  

Once the SAM issue is resolved, the README.md should be updated to remove the requirement to manually update the IAM role and then this issue can be resolved.

**Comment by ghost** [comment]
i don't believe i'm seeing this issue
