### ISSUE TITLE
Cfn_rules

### ISSUE THREAD

**Issue by hbandaru02** [stelligent/cfn-nag-pipeline#3]
How to add custom cfn_nage rules in lambda?
I have my custom rule ready but don't know where to add it.

it would be helpful for my org to use cfn_nag @PaulDuvall

**Comment by ghost** [comment]
@foobar123-del the current version published in SAR doesn't really support custom rules in a convenient way.  I'm working on bringing the SAR lambda to be up to date...

If you could load custom rules from s3, would that satisfy your use case?  I have some unreleased code to support this.

**Comment by hbandaru02** [comment]
@erickascic  
Yup that works for me...

**Comment by ghost** [comment]
@foobar123-del in 0.5.5 of the release in SAR.... you can specify a rule bucket name and a prefix at deployment time.  Any object in the bucket that matches prefix/*Rule.rb will be loaded as a custom rule.
